### ISSUE TITLE
Overwrite Configuration.xml during setup process

### ISSUE THREAD

**Issue by vkhazin** [vk-twiconnect/twiconnect-client#1]
# Overview

* Need to overwrite Configuration.xml file packaged inside cab file during the deployment with a replacement (custom) Configuration.xml that will be placed for each installation separately from wix tools
* The replacement file will be stored in the same folder with the msi file
* At the end of the setup process, but before the Windows Service starts, the setup process is to overwrite the stock file with the customer

## How to contribute

* Fork the repo
* Create a new branch in your repo: `replace-config`
* Commit changes to the new branch of your repo
* Submit a pull request to the this repo using the same branch name

**Comment by ehwest** [comment]
Using the current package.
http://68.199.43.204:6002/downloadables/download_me.htm
Which generates the initial Configuration.json on the fly, seems to be unread based
on the log file:

2018-10-01 20:34:43.0120 INFO Process started.
2018-10-01 20:34:43.0168 INFO Process failed.
2018-10-01 20:34:43.0168 TRACE Loading local configuration '.\Configuration.json'.
2018-10-01 20:34:43.0168 TRACE Reading content for file: '.\Configuration.json'.
2018-10-01 20:34:43.0328 ERROR System.IO.FileNotFoundException: Could not find file 'C:\WINDOWS\system32\Configuration.json'.
File name: 'C:\WINDOWS\system32\Configuration.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at TWIConnect.Client.Utilities.FileSystem.ReadTextFile(String filePath)
   at TWIConnect.Client.Configuration.Load()

**Comment by ehwest** [comment]
Looks like the end to end thread for ObjectType="None" is now working.
I shall add some features to pollrequest.htm to do the other cases in some kind of random way.

**Comment by ehwest** [comment]
There is still a problem with this Beta release.
https://github.com/vk-twiconnect/twiconnect-client/releases/tag/3.0.4

The problem is that the **cab** file contains a **Configuration.json**  file which during install time, is used instead of the independent Configuration.json file that is included in the exe-to-unzip package.

A key goal here was and is to provide a Configuration.json file during the construction of the .exe file.  This file is customized for each download action.  Having a non-working file in the cab file is not working.

**Comment by vkhazin** [comment]
Addressing...

**Comment by vkhazin** [comment]
Resolved in: https://github.com/vk-twiconnect/twiconnect-client/releases/tag/3.0.5

**Comment by ehwest** [comment]
ok, looks like it works now....
I just want to understand...it looks like there is still a file in the cab1.cab that is Configuration.json and it has a Uri that is http://msn.ca   Would this be expected to somehow timeout and then pick the other Configuration.json?  How does that work?   Would null for Uri work?
